baseURL: "https://liber-impro.com"
languageCode: "en-us"
title: "Liber"
disableKinds: [ "taxonomy" ]

markup:
  goldmark:
    renderer:
      unsafe: true

publishDir: docs

menu:
  main:
    - identifier: home
      url: ""
      weight: 10
    - identifier: about
      url: "about"
      weight: 15
#    - identifier: players
#      url: players/
#      weight: 20
    - identifier: workshops
      url: workshops/
      weight: 30
    - identifier: events
      url: events/
      weight: 40
    - identifier: contact
      url: contact/
      weight: 50

build:
  writeStats: true

defaultContentLanguage: fr
languages:
  fr:
    weight: 10
    languageName: 🇫🇷
  de:
    weight: 20
    languageName: 🇩🇪
#  en:
#    weight: 30
#    languageName: 🇬🇧